### ISSUE TITLE
0.15.1869 push to remote buttons disabled unless on remote

### ISSUE THREAD

**Issue by marchyman** [rowanj/gitx#318] opened 2014-05-12 23:34 UTC
The push to remote button os disabled unless I click on the remote site, in which case it doesn't know what branch to push.   Back to using the command line.

**Comment by beporter** [comment] 2014-05-14 14:49
:+1: Yeah, this is killing my workflow too.

**Comment by marchyman** [comment] 2014-05-14 19:53
Workaround: use the gear icon to the left of the cloud icons.  Select the Push master to > origin (or whatever other branch/remote you want.

**Comment by rowanj** [comment] 2014-05-15 03:52
Is this affecting the context menu on the sidebar, or on the ref labels in the history view?

**Comment by beporter** [comment] 2014-05-15 13:41
Both the sidebar context menu and the ref label context menu still have options for 

**Push `branchname` to :arrow_forward: (submenu) `remotename`**.

(Boy I **really** miss the "shortcut" entry for pushing a ref to the default (or only?) remote that used to live in the top level context menu. It seems like if there is only 1 remote, the submenu is hit to productivity, having to wait even a half-second for it to open.)

**Comment by rowanj** [comment] 2014-05-15 15:24
This was caused by my change to the latest objective-git API, which (during my fix to accommodate their changes) broke the lookup of which was the tracking branch for a given ref.

Since I use "push to -> remote name" from the refs menu, this slipped past.  Should be fixed in the upcoming build.

**Closed as completed** 2014-05-15 15:25 UTC
