### ISSUE TITLE
GitX 0.14.23 - 64-bit build doesn't work

### ISSUE THREAD

**Issue by robmathews** [rowanj/gitx#39] opened 2012-05-12 18:23 UTC
Just a heads up: 

I just downloaded 0.14.23, and it claimed every git repository I tried to open was corrupt. It also gave this warning: 

```
lapdog:code rob$ gitx 
objc[39208]: Class __ARCLite__ is implemented in both /Applications/GitX.app/Contents/Resources/../Frameworks    /ObjectiveGit.framework/Versions/A/ObjectiveGit and /usr/local/bin/gitx. One of the two will be used. Which one is undefined.
```

I then tried the previous release build 0.14.16, and it worked just fine.

This is on OSX 10.7.3.

Thanks!

**Comment by rowanj** [comment] 2012-05-13 07:55
In the span between these releases I've switched to using libgit2 to read the named refs (brances/tags) for the repository instead of parsing the output of command-line git (rowanj/gitx#2)

It seems that there's an issues in the libgit2 version we're using where it will fail to open a repository if the git configuration ( `$repository/.git/config` or `~/.gitconfig` ) can't be read, which erroneously happens if it contains strings with shell-literal encoded characters like `\"` (backslash-quote) (rowanj/gitx#33)*.  I've heard that this issue is fixed in upstream libgit2/libgit2 - so I'll be updating the bundled version of that in a new build that I hope to have out tonight.
- notably the default configuration of the SourceTree application creates lines like this in your `~/.gitconfig` file on startup.

**Comment by rowanj** [comment] 2012-05-13 08:16
I'll write up the **ARCLite** warning separately, as it is coming up fairly regularly.

Edit: rowanj/gitx#40

**Comment by rowanj** [comment] 2012-05-13 12:44
If this is a dupe of rowanj/gitx#33 (as I think it is), I expect this to be resolved in 0.14.24, released ~1h ago.

**Comment by robmathews** [comment] 2012-05-13 13:30
Many thanks for this fork, BTW. Great work speeding this one up compared to the Gitx(L) fork. That one is so slow that I couldn't use it.

**Comment by rowanj** [comment] 2012-05-14 00:39
Thanks!  I'm not really sure what's making the speed difference, I think they introduced the performance problems since I last merged any code from GitX (L); so I've been really careful about merging anything from them since I heard about the problems.

**Comment by rowanj** [comment] 2012-05-19 14:10
My impression is that this is fixed.

**Closed as completed** 2012-05-19 14:09 UTC

**Comment by robmathews** [comment] 2012-05-19 14:21
Probably. I just haven't bothered retesting, as the previous version works fine for me.

**Comment by rowanj** [comment] 2012-05-20 00:46
Sure, 0.14.16 is a relatively solid release; I'll be keeping it available on the downloads page for a while yet, I think.  I'm glad that you've got a version that works well enough for you.

You'll at least always be able to check the release notes from the updater if you find yourself pondering upgrading later; you might find something there to entice you.  :-)

**Comment by bluemont** [comment] 2012-07-18 03:57
Thanks for keeping GitX alive!

I am using GitX (R), Version 0.14.34 development (0.14.34) and I get this warning:

> objc[63561]: Class **ARCLite** is implemented in both /Applications/GitX.app/Contents/Resources/../Frameworks/ObjectiveGit.framework/Versions/A/ObjectiveGit and /usr/local/bin/gitx. One of the two will be used. Which one is undefined.

I reinstalled the command line tools just to be safe. I used to use GitX (L).

**Comment by rowanj** [comment] 2012-07-22 08:57
That's issue #40 - it's a warning only, and is safe to ignore (both versions are identical, they are built at the same time on the same machine for each build).

At this stage, the warning is likely to persist until we deprecate Snow Leopard support, and the ARCLite library stops being linked in to the products by Xcode.
