### ISSUE TITLE
Frequent "Failed to lookup reference..." when remote refs disappear

### ISSUE THREAD

**Issue by mczepiel** [rowanj/gitx#53] opened 2012-06-01 19:03 UTC
This alert is kind of annoying: "Failed to lookup reference. The given reference name is not valid"

It pops up as a result of learning about deleted remote branches (and possibly other scenarios). Regardless, it happens a lot.

At the very least it should say which ref (refs?) is now missing and not valid.

**Comment by rowanj** [comment] 2012-06-04 00:20
It's probably not actually an error at all.  I did just remove a bunch of remote branches and didn't get any pop-ups, though - is there a specific type of ref?  Does it happen more if you're on a branch tracking one at the time?  I'll try deleting the entire remote to reproduce.

edit: no effect, still can't reproduce this, but I think I know which code is producing the error and I'll try to make it be quiet.

**Comment by akirk** [comment] 2012-06-06 15:14
I have this happening sometimes (= sounds like a race condition) when I have gitx open and push changes to remote using git through a terminal window.

It started happening around 0.14.27 (unfortunately I can't find the release history file that you see within sparkle with which i could probably name the last working version).

**Comment by rowanj** [comment] 2012-06-08 05:21
Yeah, I've had it a couple of times now - I think it is quite recent.  I tend to see it when working with git-svn repositories and rebasing from an SVN branch.

The release notes are deployed from the repository itself (updates/GitX-dev.html) - to a file on the deployment host at [http://builds.phere.net/GitX/development/GitX-dev-{last_digit_of_build_number}.html](http://builds.phere.net/GitX/development/GitX-dev-27.html)  (note that only successful builds get deployed).

For the more enthusiastic, there's actually a lot more stuff in that path for each successful build, including:
- GitX-dev-{build}.zip for the packaged .app
- GitX-dev-{build}-dSYM.zip for the debug symbols

**Comment by rowanj** [comment] 2012-06-08 05:26
Note: I'm not implying that you need to find where it was introduced - I believe the bug exists and is reproducible; it will be fixed.  Just sharing how the release notes are displayed.  This isn't the first time I've thought it'd be good to be able to get back to them from within the app, so I'll add an issue to add that now.

**Closed as completed** 2012-06-10 05:51 UTC

**Comment by akirk** [comment] 2012-06-11 15:30
Great, thanks!
