### ISSUE TITLE
Traverse directories up when starting gitx from the command line

### ISSUE THREAD

**Issue by akirk** [rowanj/gitx#70] opened 2012-08-08 06:23 UTC
Through the command line I can invoke git from any directory within git control, with gitx I can't.

```
The document “www” could not be opened.
/Users/alex/project/www does not appear to be a git repository.
```

Where `/Users/alex/project/.git/` exists but not `/Users/alex/project/www/.git`.

What git does is it traverses the directory structure up until it lands in the root directory and checks each directory for a .git directory along the way. It only complains if it can find none.

gitx on the other hand just checks the current directory for a .git directory.

Would be cool if this could be changed to the way git behaves so that one can start gitx also from any directory within git control.

**Comment by rowanj** [comment] 2012-08-09 01:11
I just confirmed that it is working for me; although I did fix it in the last couple of months to do so, it now uses the libgit2 functions to find the git directory for the working directory.

Perhaps you need to re-install the command-line tools from the `GitX` menu to get the latest version?

**Comment by akirk** [comment] 2012-08-13 07:12
That does help indeed, though apart from opening the correct git repository, it also opens an "Open dialog" and on the command line I also get the message

```
objc[1581]: Class __ARCLite__ is implemented in both /Applications/GitX.app/Contents/Frameworks/ObjectiveGit.framework/Versions/A/ObjectiveGit and /usr/local/bin/gitx. One of the two will be used. Which one is undefined.
```

Any ideas?

**Comment by gomar** [comment] 2012-08-13 07:31
+1, I get that error message too when I launch gitx command line tool.

**Comment by pipelineoptika** [comment] 2012-08-13 08:05
Rowan is covering this in issue #40. Do head over there and join the conversation - opinions most welcome!

**Comment by akirk** [comment] 2012-08-13 08:07
Ah, thanks for pointing that out. So for me only the problem remains that it opens an unnecessary "Open" window when launching `gitx` from another directory than the one with the `.git` directory.

**Comment by digitalresistor** [comment] 2012-11-15 19:58
@akirk It looks like it no longer opens an "Open ..." window when you open it from a non-.git containing directory and it has to do its backwards search.

This should be fixed :-)

**Comment by rowanj** [comment] 2012-11-16 03:41
Yep, it shouldn't be opening the "Open ..." window implicitly at all anymore.

**Closed as completed by rowanj** 2012-11-16 03:41 UTC

**Comment by akirk** [comment] 2012-11-16 06:55
Very good, thanks @rowanj!
